# Generated by Django 4.1.5 on 2023-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.ManyToManyField(to='student.classes'),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='note_ds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='note_ex',
            field=models.FloatField(null=True),
        ),
    ]